//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public string ItemQty { get; set; }
        public string ItemPrice { get; set; }
    }
}
